### ISSUE TITLE
Update dconf to build / work properly on RHEL6

### ISSUE THREAD

**Issue by zyv** [dagwieers/dconf#1]
See https://github.com/repoforge/rpms/issues/42 .

You can use my patches for mrepo to see how to solve the md5 / sha1 issues.

**Comment by dagwieers** [comment]
Thanks, both the md5/sha1 issues has been fixed, as well as the popen2 issue. Compatibility with older python release is harmed due to the dependency to subprocess. Python 2.4 is required.

**Comment by zyv** [comment]
> Compatibility with older python release is harmed due to the dependency to subprocess. Python 2.4 is required.

This is very easy to fix in the same way I did by trying to import subprocess and falling back to popen if it fails, this way you can still have it working on older Pythons. Do you need help with this?

**Comment by dagwieers** [comment]
On Mon, 12 Sep 2011, Yury V. Zaytsev wrote:

> > Compatibility with older python release is harmed due to the dependency to subprocess. Python 2.4 is required.
> 
> This is very easy to fix in the same way I did by trying to import 
> subprocess and falling back to popen if it fails, this way you can still 
> have it working on older Pythons. Do you need help with this?

Right, but it means having to do that for two occurances in runtime and I 
don't know if it makes a lot of sense to keep on supporting RHEL4 and 
older in the future.

It's not that I don't know how to do it, but rather whether it makes sense 
to still do it in this case. I can be convinced otherwise though ;-)

hashlib is different because that requires python 2.5, which would 
unsupport RHEL5 too.

## 

-- dag wieers, dag@wieers.com, http://dag.wieers.com/
-- dagit linux solutions, info@dagit.net, http://dagit.net/

[Any errors in spelling, tact or fact are transmission errors]

**Comment by zyv** [comment]
On Mon, 2011-09-12 at 04:45 -0700, Dag Wieërs wrote:

> Right, but it means having to do that for two occurances in runtime and I 
> don't know if it makes a lot of sense to keep on supporting RHEL4 and 
> older in the future.

I was assuming that RHEL4 is still important, and since you used to care
a lot about RHEL2/3, I was thinking that you'd want to support RHEL4 as
it only requires 5 lines of code.

If you think it's not worth it, I digress; after all I've only got one
RHEL4 machine left these days and it will probably be decommissioned at
some point... :-)

## 

Sincerely yours,
Yury V. Zaytsev

**Comment by dagwieers** [comment]
Alright, you win again :-)

While trying to make my case I noticed it all depended on my personal situation (which is subject to change). So I figured dconf shouldn't only depend on my situation. Thanks for making that clear ;-) Patch is ready.

PS Although I stopped supporting python 1.5 (RHEL2) in dstat only last year ;-) I don't plan to add RHEL2 support :-D

**Comment by zyv** [comment]
> Alright, you win again :-)

Sorry, I didn't mean to alienate you ;-) But thanks for the fix.

I could help myself leaving a comment to the commit though. Someone has to be a PITA here... >:-)
